// Interaktywna mapa łowisk oparta na OpenStreetMap (Leaflet).
// Każde łowisko ma opis, główne gatunki i link do zewnętrznego źródła.
(function () {
  const el = document.getElementById('fishing-map');
  if (!el || typeof L === 'undefined') return;

  const LOWISKA = [
    {
      name: 'Jezioro Śniardwy',
      coords: [53.75, 21.73],
      desc: 'Największe jezioro w Polsce (Mazury). Szczupak, okoń, sandacz, leszcz, węgorz. Wody PZW Okręg Olsztyn.',
      link: 'https://pl.wikipedia.org/wiki/%C5%9Aniardwy',
    },
    {
      name: 'Jezioro Mamry',
      coords: [54.13, 21.72],
      desc: 'Głębokie, czyste jezioro mazurskie. Sieja, sielawa, szczupak, duży okoń. Świetne na trolling i spinning z łodzi.',
      link: 'https://pl.wikipedia.org/wiki/Mamry',
    },
    {
      name: 'Zalew Zegrzyński',
      coords: [52.45, 21.05],
      desc: 'Najpopularniejsze łowisko aglomeracji warszawskiej. Sandacz, szczupak, boleń, leszcz. Łatwy dojazd, dużo miejscówek z brzegu.',
      link: 'https://pl.wikipedia.org/wiki/Jezioro_Zegrzy%C5%84skie',
    },
    {
      name: 'Jezioro Solińskie',
      coords: [49.4, 22.45],
      desc: 'Największy sztuczny zbiornik w Polsce (Bieszczady). Sandacz, szczupak, okoń, troć jeziorowa. Głębokości do 60 m — przydatna echosonda.',
      link: 'https://pl.wikipedia.org/wiki/Jezioro_Soli%C5%84skie',
    },
    {
      name: 'Zbiornik Włocławski (Wisła)',
      coords: [52.62, 19.32],
      desc: 'Zbiornik zaporowy na Wiśle. Słynie z dużych sumów i sandaczy, liczny boleń. Łowienie z łodzi i z brzegu.',
      link: 'https://pl.wikipedia.org/wiki/Zbiornik_W%C5%82oc%C5%82awski',
    },
    {
      name: 'Odra — Bytom Odrzański',
      coords: [51.73, 15.82],
      desc: 'Klasyczny odcinek Odry z ostrogami. Boleń, sandacz, sum, brzana, kleń. Mekka spinningistów rzecznych.',
      link: 'https://pl.wikipedia.org/wiki/Odra',
    },
    {
      name: 'San — odcinek górski',
      coords: [49.47, 22.33],
      desc: 'Słynna woda muchowa poniżej zapory w Myczkowcach. Lipień, pstrąg potokowy. Obowiązują łowiska specjalne i limity.',
      link: 'https://pl.wikipedia.org/wiki/San',
    },
    {
      name: 'Jeziorak',
      coords: [53.7, 19.55],
      desc: 'Najdłuższe jezioro w Polsce (27 km). Szczupak, lin, leszcz, węgorz. Mnóstwo zatok i trzcinowisk — raj dla łodzi.',
      link: 'https://pl.wikipedia.org/wiki/Jeziorak',
    },
    {
      name: 'Zalew Sulejowski',
      coords: [51.42, 19.97],
      desc: 'Zbiornik na Pilicy koło Tomaszowa Maz. Sandacz, szczupak, okoń, leszcz. Popularne łowisko centralnej Polski.',
      link: 'https://pl.wikipedia.org/wiki/Zalew_Sulejowski',
    },
    {
      name: 'Jezioro Miedwie',
      coords: [53.28, 14.89],
      desc: 'Wielkie jezioro pod Szczecinem. Sandacz (jedne z najlepszych łowisk w kraju), sieja, okoń, węgorz.',
      link: 'https://pl.wikipedia.org/wiki/Miedwie',
    },
    {
      name: 'Jezioro Hańcza',
      coords: [54.27, 22.81],
      desc: 'Najgłębsze jezioro w Polsce (108 m), Suwalszczyzna. Sieja, sielawa, duży okoń i szczupak. Krystaliczna woda.',
      link: 'https://pl.wikipedia.org/wiki/Ha%C5%84cza_(jezioro)',
    },
    {
      name: 'Jezioro Wigry',
      coords: [54.03, 23.08],
      desc: 'Perła Suwalszczyzny w granicach Wigierskiego PN. Sieja, sielawa, szczupak, lin. Łowienie wg regulaminu parku.',
      link: 'https://pl.wikipedia.org/wiki/Wigry_(jezioro)',
    },
    {
      name: 'Jezioro Niegocin',
      coords: [54.0, 21.77],
      desc: 'Duże jezioro przy Giżycku, łatwy dostęp i wypożyczalnie łodzi. Szczupak, sandacz, okoń, leszcz, węgorz.',
      link: 'https://pl.wikipedia.org/wiki/Niegocin',
    },
    {
      name: 'Jezioro Nidzkie',
      coords: [53.6, 21.55],
      desc: 'Rynnowe jezioro koło Rucianego-Nidy, otoczone Puszczą Piską. Szczupak, lin, leszcz, węgorz. Strefa ciszy.',
      link: 'https://pl.wikipedia.org/wiki/Jezioro_Nidzkie',
    },
    {
      name: 'Jezioro Drawsko',
      coords: [53.6, 16.18],
      desc: 'Drugie najgłębsze jezioro Polski (Pojezierze Drawskie). Sieja, sielawa, szczupak, okoń, węgorz.',
      link: 'https://pl.wikipedia.org/wiki/Drawsko_(jezioro)',
    },
    {
      name: 'Jezioro Dąbie',
      coords: [53.5, 14.65],
      desc: 'Wielkie płytkie jezioro przy ujściu Odry (Szczecin). Sandacz, szczupak, sum, okoń, boleń. Łowisko łodziowe.',
      link: 'https://pl.wikipedia.org/wiki/D%C4%85bie_(jezioro)',
    },
    {
      name: 'Zalew Szczeciński',
      coords: [53.78, 14.4],
      desc: 'Ogromny przymorski akwen. Sandacz w ilościach niespotykanych, okoń, certa, węgorz. Wymagana łódź i ostrożność przy wietrze.',
      link: 'https://pl.wikipedia.org/wiki/Zalew_Szczeci%C5%84ski',
    },
    {
      name: 'Zatoka Pucka',
      coords: [54.66, 18.5],
      desc: 'Płytka zatoka Bałtyku. Troć wędrowna, belona wiosną, okoń, płastugi. Spinning i surfcasting.',
      link: 'https://pl.wikipedia.org/wiki/Zatoka_Pucka',
    },
    {
      name: 'Jezioro Charzykowskie',
      coords: [53.77, 17.5],
      desc: 'Duże jezioro na skraju Borów Tucholskich. Sielawa, szczupak, sandacz, okoń, węgorz.',
      link: 'https://pl.wikipedia.org/wiki/Charzykowskie',
    },
    {
      name: 'Jezioro Gopło',
      coords: [52.58, 18.35],
      desc: 'Długie, płytkie jezioro na Kujawach. Sandacz, szczupak, lin, karaś, węgorz. Dużo trzcinowisk.',
      link: 'https://pl.wikipedia.org/wiki/Gop%C5%82o',
    },
    {
      name: 'Jezioro Powidzkie',
      coords: [52.42, 17.95],
      desc: 'Najczystsze duże jezioro Wielkopolski. Sieja, sielawa, duży szczupak i okoń. Popularne łowisko trollingowe.',
      link: 'https://pl.wikipedia.org/wiki/Jezioro_Powidzkie',
    },
    {
      name: 'Zbiornik Jeziorsko (Warta)',
      coords: [51.73, 18.7],
      desc: 'Wielki zbiornik zaporowy na Warcie. Sandacz, boleń, sum, okoń. Duże wahania poziomu wody.',
      link: 'https://pl.wikipedia.org/wiki/Jeziorsko',
    },
    {
      name: 'Zbiornik Mietków (Bystrzyca)',
      coords: [50.96, 16.6],
      desc: 'Największy zbiornik Dolnego Śląska. Sandacz, szczupak, okoń, karp. Popularne łowisko spinningowe pod Wrocławiem.',
      link: 'https://pl.wikipedia.org/wiki/Zbiornik_Mietkowski',
    },
    {
      name: 'Zbiornik Otmuchowski (Nysa Kłodzka)',
      coords: [50.45, 17.12],
      desc: 'Zbiornik zaporowy na Opolszczyźnie. Sandacz, sum, boleń, leszcz. Obok bliźniaczy zbiornik Nyski.',
      link: 'https://pl.wikipedia.org/wiki/Jezioro_Otmuchowskie',
    },
    {
      name: 'Zbiornik Goczałkowicki (Wisła)',
      coords: [49.93, 18.87],
      desc: 'Wielki zbiornik na górnej Wiśle (Śląsk). Sandacz, szczupak, sum, leszcz. Część akwenu objęta ochroną.',
      link: 'https://pl.wikipedia.org/wiki/Jezioro_Gocza%C5%82kowickie',
    },
    {
      name: 'Jezioro Żywieckie (Soła)',
      coords: [49.72, 19.22],
      desc: 'Górski zbiornik zaporowy w Beskidach. Sandacz, szczupak, okoń, pstrąg potokowy w dopływach.',
      link: 'https://pl.wikipedia.org/wiki/Jezioro_%C5%BBywieckie',
    },
    {
      name: 'Jezioro Rożnowskie (Dunajec)',
      coords: [49.75, 20.7],
      desc: 'Zbiornik na Dunajcu (Małopolska). Sandacz, szczupak, boleń, brzana i świnka w cofce.',
      link: 'https://pl.wikipedia.org/wiki/Jezioro_Ro%C5%BCnowskie',
    },
    {
      name: 'Jezioro Czorsztyńskie (Dunajec)',
      coords: [49.45, 20.32],
      desc: 'Górski zbiornik pod Pieninami. Szczupak, sandacz, okoń, pstrąg. Malownicze łowisko z widokiem na zamki.',
      link: 'https://pl.wikipedia.org/wiki/Jezioro_Czorszty%C5%84skie',
    },
    {
      name: 'Dunajec poniżej Czorsztyna',
      coords: [49.42, 20.43],
      desc: 'Słynne łowisko pstrągowe „za zaporą" (Sromowce–Szczawnica). Pstrąg potokowy, lipień, głowacica. Woda górska.',
      link: 'https://pl.wikipedia.org/wiki/Dunajec',
    },
    {
      name: 'Zbiornik Siemianówka (Narew)',
      coords: [52.92, 23.72],
      desc: 'Płytki zbiornik na skraju Puszczy Białowieskiej. Słynie z wielkich szczupaków i karasi; sum, lin.',
      link: 'https://pl.wikipedia.org/wiki/Zbiornik_Siemian%C3%B3wka',
    },
    {
      name: 'Biebrza',
      coords: [53.5, 22.6],
      desc: 'Dzika rzeka bagiennej doliny. Szczupak, okoń, jaź, wzdręga. Łowienie w granicach Biebrzańskiego PN wg regulaminu.',
      link: 'https://pl.wikipedia.org/wiki/Biebrza',
    },
    {
      name: 'Narew — Dolina Dolnej Narwi',
      coords: [52.9, 21.7],
      desc: 'Nizinny, kręty odcinek Narwi. Szczupak, sum, jaź, kleń, boleń. Klasyka łowienia rzecznego z łodzi.',
      link: 'https://pl.wikipedia.org/wiki/Narew',
    },
    {
      name: 'Bug — środkowy odcinek',
      coords: [52.45, 22.3],
      desc: 'Dzika, nieuregulowana rzeka. Sum, boleń, sandacz, kleń, jaź. Piaszczyste łachy i głębokie rynny.',
      link: 'https://pl.wikipedia.org/wiki/Bug',
    },
    {
      name: 'Wisła — Warszawa',
      coords: [52.24, 21.04],
      desc: 'Miejski odcinek dzikiej rzeki. Boleń, sum, sandacz, brzana, kleń. Łowienie z kamienistych ostróg.',
      link: 'https://pl.wikipedia.org/wiki/Wis%C5%82a',
    },
    {
      name: 'Pilica',
      coords: [51.55, 20.3],
      desc: 'Czysta nizinna rzeka. Kleń, jaź, boleń, szczupak, brzana. Dobre łowisko spinningowe i muchowe.',
      link: 'https://pl.wikipedia.org/wiki/Pilica_(rzeka)',
    },
    {
      name: 'Warta — Poznań i okolice',
      coords: [52.4, 16.93],
      desc: 'Duża nizinna rzeka. Sum, sandacz, boleń, kleń, leszcz. Liczne ostrogi i starorzecza.',
      link: 'https://pl.wikipedia.org/wiki/Warta',
    },
    {
      name: 'Drawa',
      coords: [53.2, 15.9],
      desc: 'Szybka rzeka pojezierna (Drawieński PN). Pstrąg potokowy, lipień, kleń. Łowisko dla muszkarzy i spławikowców.',
      link: 'https://pl.wikipedia.org/wiki/Drawa_(dop%C5%82yw_Noteci)',
    },
    {
      name: 'Gwda',
      coords: [53.3, 16.75],
      desc: 'Rzeka pstrągowo-lipieniowa północnej Wielkopolski. Pstrąg, lipień, kleń, szczupak na spokojniejszych odcinkach.',
      link: 'https://pl.wikipedia.org/wiki/Gwda',
    },
    {
      name: 'Wda',
      coords: [53.55, 18.3],
      desc: 'Malownicza rzeka Borów Tucholskich. Pstrąg, lipień, kleń, szczupak. Popularny szlak kajakowo-wędkarski.',
      link: 'https://pl.wikipedia.org/wiki/Wda',
    },
    {
      name: 'Słupia',
      coords: [54.35, 17.05],
      desc: 'Pomorska rzeka trociowa. Troć wędrowna (sezon jesienno-zimowy), pstrąg, lipień. Wymagane zezwolenia specjalne.',
      link: 'https://pl.wikipedia.org/wiki/S%C5%82upia',
    },
    {
      name: 'Parsęta',
      coords: [54.05, 15.85],
      desc: 'Jedna z najlepszych polskich rzek trociowych. Troć wędrowna, łosoś, pstrąg, lipień.',
      link: 'https://pl.wikipedia.org/wiki/Pars%C4%99ta',
    },
    {
      name: 'Wisłoka',
      coords: [49.9, 21.4],
      desc: 'Podkarpacka rzeka o górskim charakterze w górnym biegu. Brzana, świnka, kleń, pstrąg.',
      link: 'https://pl.wikipedia.org/wiki/Wis%C5%82oka',
    },

    // --- Mazury, Warmia, Suwalszczyzna, Podlasie ---
    {
      name: 'Jezioro Tałty',
      coords: [53.73, 21.55],
      desc: 'Długie, rynnowe jezioro szlaku Wielkich Jezior Mazurskich. Łowi się tu szczupaki, sandacze, okonie i leszcze.',
      link: 'https://pl.wikipedia.org/wiki/Ta%C5%82ty',
    },
    {
      name: 'Jezioro Roś',
      coords: [53.62, 21.87],
      desc: 'Rozległe jezioro koło Pisza, przez które przepływa Pisa. Znane z sandaczy, szczupaków, leszczy i węgorzy.',
      link: 'https://pl.wikipedia.org/wiki/Ro%C5%9B_(jezioro)',
    },
    {
      name: 'Jezioro Bełdany',
      coords: [53.67, 21.57],
      desc: 'Rynnowe jezioro łączące Mikołajki z Rucianem-Nidą, otoczone Puszczą Piską. Dobre łowisko szczupaka, okonia i siei.',
      link: 'https://pl.wikipedia.org/wiki/Be%C5%82dany',
    },
    {
      name: 'Jezioro Tałtowisko',
      coords: [53.85, 21.55],
      desc: 'Głębokie jezioro rynnowe na szlaku Wielkich Jezior Mazurskich. Występują tu sieja, sielawa, szczupak i okoń.',
      link: 'https://pl.wikipedia.org/wiki/Ta%C5%82towisko',
    },
    {
      name: 'Jezioro Kisajno',
      coords: [54.07, 21.73],
      desc: 'Północna część kompleksu Mamr z licznymi wyspami. Łowisko szczupaków, okoni, sandaczy i leszczy.',
      link: 'https://pl.wikipedia.org/wiki/Kisajno',
    },
    {
      name: 'Jezioro Dargin',
      coords: [54.12, 21.72],
      desc: 'Rozległe jezioro kompleksu Mamr o czystej wodzie. Dobre łowisko sandacza, szczupaka i dużego okonia.',
      link: 'https://pl.wikipedia.org/wiki/Dargin',
    },
    {
      name: 'Jezioro Dobskie',
      coords: [54.09, 21.65],
      desc: 'Jezioro w kompleksie Mamr objęte rezerwatem ornitologicznym. Słynie z dużych szczupaków, okoni i sielawy.',
      link: 'https://pl.wikipedia.org/wiki/Jezioro_Dobskie',
    },
    {
      name: 'Jezioro Łuknajno',
      coords: [53.81, 21.63],
      desc: 'Płytkie jezioro koło Mikołajek, rezerwat biosfery słynący z łabędzi. W wodach dominują liny, karasie i szczupaki.',
      link: 'https://pl.wikipedia.org/wiki/%C5%81uknajno',
    },
    {
      name: 'Jezioro Mikołajskie',
      coords: [53.78, 21.58],
      desc: 'Rynnowe jezioro łączące Tałty ze Śniardwami, w sercu Mazur. Łowi się tu sandacze, szczupaki, węgorze i leszcze.',
      link: 'https://pl.wikipedia.org/wiki/Jezioro_Miko%C5%82ajskie',
    },
    {
      name: 'Jezioro Jagodne',
      coords: [53.93, 21.71],
      desc: 'Jezioro na szlaku Wielkich Jezior między Niegocinem a Tałtami. Dobre łowisko szczupaka, okonia i leszcza.',
      link: 'https://pl.wikipedia.org/wiki/Jagodne_(jezioro)',
    },
    {
      name: 'Jezioro Szymon',
      coords: [53.89, 21.60],
      desc: 'Płytkie, zarastające jezioro na szlaku Wielkich Jezior Mazurskich. Królują tu szczupaki, liny i karasie.',
      link: 'https://pl.wikipedia.org/wiki/Szymon_(jezioro)',
    },
    {
      name: 'Jezioro Orzysz',
      coords: [53.83, 21.93],
      desc: 'Rozległe jezioro morenowe z licznymi wyspami koło miasta Orzysz. Łowisko sielawy, szczupaka, okonia i leszcza.',
      link: 'https://pl.wikipedia.org/wiki/Orzysz_(jezioro)',
    },
    {
      name: 'Jezioro Buwełno',
      coords: [53.87, 21.78],
      desc: 'Głębokie jezioro rynnowe między Niegocinem a Śniardwami. Występują tu sieja, sielawa, szczupak i duże okonie.',
      link: 'https://pl.wikipedia.org/wiki/Buwe%C5%82no',
    },
    {
      name: 'Jezioro Wojnowo',
      coords: [53.90, 21.81],
      desc: 'Spokojne jezioro w pobliżu Buwełna na Mazurach. Dobre łowisko szczupaka, lina i leszcza.',
      link: 'https://pl.wikipedia.org/wiki/Wojnowo_(jezioro)',
    },
    {
      name: 'Jezioro Ublik Wielki',
      coords: [53.86, 21.86],
      desc: 'Czyste, głębokie jezioro koło Orzysza. Łowi się tu sielawę, szczupaka, okonia i węgorza.',
      link: 'https://pl.wikipedia.org/wiki/Ublik_Wielki',
    },
    {
      name: 'Jezioro Mokre',
      coords: [53.65, 21.43],
      desc: 'Głębokie jezioro w Puszczy Piskiej koło Zgonu. Znane z siei, sielawy, szczupaków i dużych okoni.',
      link: 'https://pl.wikipedia.org/wiki/Mokre_(jezioro_w_powiecie_mr%C4%85gowskim)',
    },
    {
      name: 'Jezioro Wałpusz',
      coords: [53.65, 21.10],
      desc: 'Jezioro rynnowe koło Szczytna otoczone lasami. Łowisko szczupaka, okonia, leszcza i węgorza.',
      link: 'https://pl.wikipedia.org/wiki/Wa%C5%82pusz',
    },
    {
      name: 'Jezioro Sasek Wielki',
      coords: [53.62, 20.96],
      desc: 'Duże jezioro rynnowe na północ od Szczytna. Dobre łowisko sandacza, szczupaka, leszcza i sielawy.',
      link: 'https://pl.wikipedia.org/wiki/Sasek_Wielki',
    },
    {
      name: 'Jezioro Omulew',
      coords: [53.55, 20.65],
      desc: 'Rozległe jezioro z wyspami na skraju Puszczy Napiwodzko-Ramuckiej. Łowi się tu sielawę, szczupaka, okonia i lina.',
      link: 'https://pl.wikipedia.org/wiki/Omulew_(jezioro)',
    },
    {
      name: 'Jezioro Pluszne',
      coords: [53.62, 20.40],
      desc: 'Głębokie, czyste jezioro koło Olsztynka na Warmii. Występują tu sieja, sielawa, sandacz i duży okoń.',
      link: 'https://pl.wikipedia.org/wiki/Pluszne',
    },
    {
      name: 'Jezioro Łańskie',
      coords: [53.58, 20.55],
      desc: 'Jedno z największych i najgłębszych jezior Pojezierza Olsztyńskiego, otoczone lasami. Słynie z siei, sielawy i dużych szczupaków.',
      link: 'https://pl.wikipedia.org/wiki/%C5%81a%C5%84skie_(jezioro)',
    },
    {
      name: 'Jezioro Ukiel',
      coords: [53.79, 20.43],
      desc: 'Największe jezioro w granicach Olsztyna, popularne wśród miejskich wędkarzy. Łowi się tu okonie, szczupaki, sandacze i leszcze.',
      link: 'https://pl.wikipedia.org/wiki/Ukiel',
    },
    {
      name: 'Jezioro Dadaj',
      coords: [53.87, 20.87],
      desc: 'Duże jezioro morenowe koło Biskupca z urozmaiconą linią brzegową. Dobre łowisko sandacza, szczupaka, węgorza i siei.',
      link: 'https://pl.wikipedia.org/wiki/Dadaj',
    },
    {
      name: 'Jezioro Luterskie',
      coords: [53.95, 20.84],
      desc: 'Czyste jezioro morenowe na Warmii koło Lutr. Występują tu sielawa, sieja, szczupak i okoń.',
      link: 'https://pl.wikipedia.org/wiki/Luterskie',
    },
    {
      name: 'Jezioro Lampackie',
      coords: [53.78, 21.18],
      desc: 'Jezioro rynnowe koło Sorkwit na Pojezierzu Mrągowskim. Łowisko szczupaka, okonia, leszcza i lina.',
      link: 'https://pl.wikipedia.org/wiki/Lampackie',
    },
    {
      name: 'Jezioro Juno',
      coords: [53.89, 21.27],
      desc: 'Rynnowe jezioro na północ od Mrągowa. Dobre łowisko sandacza, szczupaka, węgorza i leszcza.',
      link: 'https://pl.wikipedia.org/wiki/Juno_(jezioro)',
    },
    {
      name: 'Jezioro Gołdopiwo',
      coords: [54.13, 21.87],
      desc: 'Duże jezioro koło Kruklanek na wschodnich Mazurach. Słynie z sielawy, siei, szczupaków i okoni.',
      link: 'https://pl.wikipedia.org/wiki/Go%C5%82dopiwo',
    },
    {
      name: 'Jezioro Litygajno',
      coords: [53.98, 22.15],
      desc: 'Rynnowe jezioro w Puszczy Boreckiej. Łowi się tu sielawę, szczupaka, okonia i lina.',
      link: 'https://pl.wikipedia.org/wiki/Litygajno',
    },
    {
      name: 'Jezioro Łaśmiady',
      coords: [53.92, 22.30],
      desc: 'Duże jezioro koło Ełku na Pojezierzu Ełckim. Dobre łowisko sandacza, szczupaka, sielawy i węgorza.',
      link: 'https://pl.wikipedia.org/wiki/%C5%81a%C5%9Bmiady',
    },
    {
      name: 'Jezioro Selmęt Wielki',
      coords: [53.78, 22.48],
      desc: 'Rozległe jezioro na południowy wschód od Ełku z licznymi zatokami. Łowisko leszcza, szczupaka, sandacza i okonia.',
      link: 'https://pl.wikipedia.org/wiki/Selm%C4%99t_Wielki',
    },
    {
      name: 'Jezioro Ełckie',
      coords: [53.81, 22.35],
      desc: 'Rynnowe jezioro, nad którym leży miasto Ełk. Popularne łowisko sandacza, okonia, szczupaka i leszcza.',
      link: 'https://pl.wikipedia.org/wiki/Jezioro_E%C5%82ckie',
    },
    {
      name: 'Jezioro Rajgrodzkie',
      coords: [53.75, 22.65],
      desc: 'Rozgałęzione jezioro rynnowe na pograniczu Mazur i Podlasia. Znane z dużych sandaczy, szczupaków, leszczy i węgorzy.',
      link: 'https://pl.wikipedia.org/wiki/Jezioro_Rajgrodzkie',
    },
    {
      name: 'Jezioro Necko',
      coords: [53.86, 22.95],
      desc: 'Jezioro rynnowe nad Augustowem, przez które przepływa rzeka Netta. Łowisko sielawy, szczupaka, okonia i leszcza.',
      link: 'https://pl.wikipedia.org/wiki/Necko',
    },
    {
      name: 'Jezioro Białe Augustowskie',
      coords: [53.87, 23.02],
      desc: 'Czyste jezioro na szlaku Kanału Augustowskiego w Puszczy Augustowskiej. Występują tu sieja, sielawa, szczupak i okoń.',
      link: 'https://pl.wikipedia.org/wiki/Bia%C5%82e_Augustowskie',
    },
    {
      name: 'Jezioro Studzieniczne',
      coords: [53.86, 23.08],
      desc: 'Głębokie jezioro w Puszczy Augustowskiej na szlaku Kanału Augustowskiego. Dobre łowisko sielawy, siei, szczupaka i węgorza.',
      link: 'https://pl.wikipedia.org/wiki/Studzieniczne',
    },
    {
      name: 'Jezioro Sajno',
      coords: [53.82, 23.00],
      desc: 'Duże, leśne jezioro na południe od Augustowa. Łowi się tu sandacze, szczupaki, leszcze i węgorze.',
      link: 'https://pl.wikipedia.org/wiki/Sajno',
    },
    {
      name: 'Jezioro Serwy',
      coords: [53.92, 23.16],
      desc: 'Głębokie, krystalicznie czyste jezioro w Puszczy Augustowskiej. Słynie z sielawy, siei, dużych okoni i szczupaków.',
      link: 'https://pl.wikipedia.org/wiki/Serwy_(jezioro)',
    },
    {
      name: 'Czarna Hańcza',
      coords: [54.03, 23.20],
      desc: 'Najsłynniejsza rzeka Suwalszczyzny, płynąca przez Wigry i Puszczę Augustowską. W górnym biegu pstrąg i lipień, niżej szczupak, okoń i jaź.',
      link: 'https://pl.wikipedia.org/wiki/Czarna_Ha%C5%84cza',
    },
    {
      name: 'Rospuda',
      coords: [53.92, 22.93],
      desc: 'Malownicza rzeka łącząca jeziora Suwalszczyzny, uchodząca do Necka. Łowisko pstrąga, lipienia, jazia i szczupaka.',
      link: 'https://pl.wikipedia.org/wiki/Rospuda',
    },
    {
      name: 'Pisa',
      coords: [53.45, 21.80],
      desc: 'Nizinna, meandrująca rzeka łącząca jezioro Roś z Narwią, płynąca przez Puszczę Piską. Znana z sumów, szczupaków, jazi i bolenia.',
      link: 'https://pl.wikipedia.org/wiki/Pisa_(rzeka)',
    },

    // --- Pomorze, Kaszuby, wybrzeże, Żuławy ---
    {
      name: 'Jezioro Wdzydze',
      coords: [53.97, 17.92],
      desc: 'Rozległe jezioro rynnowe na Kaszubach, zwane „kaszubskim morzem". Słynie z troci jeziorowej, sandacza, szczupaka i okonia.',
      link: 'https://pl.wikipedia.org/wiki/Wdzydze_(jezioro)',
    },
    {
      name: 'Jezioro Łebsko',
      coords: [54.71, 17.4],
      desc: 'Największe jezioro przymorskie w Polsce, na terenie Słowińskiego Parku Narodowego. Woda lekko słonawa, łowi się tu węgorza, sandacza, leszcza i okonia.',
      link: 'https://pl.wikipedia.org/wiki/%C5%81ebsko',
    },
    {
      name: 'Jezioro Gardno',
      coords: [54.65, 17.13],
      desc: 'Płytkie jezioro przymorskie połączone ze Słupią. Znane z obfitych połowów leszcza, płoci, sandacza i węgorza.',
      link: 'https://pl.wikipedia.org/wiki/Gardno_(jezioro)',
    },
    {
      name: 'Jezioro Jamno',
      coords: [54.27, 16.15],
      desc: 'Przymorskie jezioro pod Koszalinem, oddzielone od Bałtyku wąską mierzeją. Dominują leszcz, płoć, sandacz i węgorz.',
      link: 'https://pl.wikipedia.org/wiki/Jamno_(jezioro)',
    },
    {
      name: 'Jezioro Bukowo',
      coords: [54.34, 16.27],
      desc: 'Płytkie jezioro przymorskie koło Dąbek. Dobre łowisko sandacza, szczupaka, leszcza i węgorza.',
      link: 'https://pl.wikipedia.org/wiki/Bukowo_(jezioro)',
    },
    {
      name: 'Jezioro Wicko',
      coords: [54.55, 16.6],
      desc: 'Jezioro przymorskie między Darłowem a Ustką. Łowisko leszcza, płoci, szczupaka i okonia.',
      link: 'https://pl.wikipedia.org/wiki/Wicko_(jezioro)',
    },
    {
      name: 'Jezioro Kopań',
      coords: [54.47, 16.47],
      desc: 'Przymorskie jezioro koło Darłowa, oddzielone od morza wąską mierzeją. Poławiane są tu sandacz, węgorz, leszcz i okoń.',
      link: 'https://pl.wikipedia.org/wiki/Kopa%C5%84_(jezioro)',
    },
    {
      name: 'Jezioro Resko Przymorskie',
      coords: [54.13, 15.37],
      desc: 'Słonawe jezioro przymorskie między Dźwirzynem a Rogowem. Znane z węgorza, sandacza, okonia i leszcza.',
      link: 'https://pl.wikipedia.org/wiki/Resko_Przymorskie',
    },
    {
      name: 'Jezioro Żarnowieckie',
      coords: [54.75, 18.08],
      desc: 'Głębokie jezioro rynnowe na północnych Kaszubach. Łowisko sielawy, siei, szczupaka, okonia i węgorza.',
      link: 'https://pl.wikipedia.org/wiki/Jezioro_%C5%BBarnowieckie',
    },
    {
      name: 'Jezioro Raduńskie Górne',
      coords: [54.25, 17.98],
      desc: 'Czyste, głębokie jezioro rynnowe w sercu Kaszub. Występują sielawa, sieja, okoń i szczupak.',
      link: 'https://pl.wikipedia.org/wiki/Radu%C5%84skie_G%C3%B3rne',
    },
    {
      name: 'Jezioro Raduńskie Dolne',
      coords: [54.3, 18.02],
      desc: 'Część raduńskiej rynny jeziornej na Kaszubach. Dobre łowisko okonia, szczupaka, leszcza i sielawy.',
      link: 'https://pl.wikipedia.org/wiki/Radu%C5%84skie_Dolne',
    },
    {
      name: 'Jezioro Ostrzyckie',
      coords: [54.27, 18.1],
      desc: 'Malownicze jezioro w Szwajcarii Kaszubskiej u stóp Wieżycy. Łowi się tu szczupaka, leszcza, okonia i płoć.',
      link: 'https://pl.wikipedia.org/wiki/Jezioro_Ostrzyckie',
    },
    {
      name: 'Jezioro Gowidlińskie',
      coords: [54.27, 17.78],
      desc: 'Duże jezioro rynnowe na zachodnich Kaszubach. Znane ze szczupaka, okonia, leszcza i węgorza.',
      link: 'https://pl.wikipedia.org/wiki/Jezioro_Gowidli%C5%84skie',
    },
    {
      name: 'Jezioro Mausz',
      coords: [54.2, 17.7],
      desc: 'Czyste jezioro rynnowe koło Sulęczyna na Kaszubach. Łowisko sielawy, szczupaka, okonia i lina.',
      link: 'https://pl.wikipedia.org/wiki/Mausz',
    },
    {
      name: 'Jezioro Jasień',
      coords: [54.32, 17.5],
      desc: 'Rozległe, czyste jezioro na Pojezierzu Bytowskim, źródłowy akwen Łupawy. Występują sielawa, sieja, szczupak i okoń.',
      link: 'https://pl.wikipedia.org/wiki/Jasie%C5%84_(jezioro)',
    },
    {
      name: 'Jezioro Wielimie',
      coords: [53.74, 16.78],
      desc: 'Duże, płytkie jezioro koło Szczecinka, przez które przepływa Gwda. Słynie z leszcza, szczupaka, sandacza i węgorza.',
      link: 'https://pl.wikipedia.org/wiki/Wielimie',
    },
    {
      name: 'Jezioro Pile',
      coords: [53.65, 16.45],
      desc: 'Głębokie jezioro koło Bornego Sulinowa na Pojezierzu Drawskim. Łowisko sielawy, siei, szczupaka i okonia.',
      link: 'https://pl.wikipedia.org/wiki/Pile_(jezioro)',
    },
    {
      name: 'Jezioro Trzesiecko',
      coords: [53.7, 16.68],
      desc: 'Miejskie jezioro Szczecinka, popularne wśród wędkarzy. Dominują leszcz, płoć, szczupak i okoń.',
      link: 'https://pl.wikipedia.org/wiki/Trzesiecko',
    },
    {
      name: 'Jezioro Lubie',
      coords: [53.45, 15.88],
      desc: 'Duże jezioro rynnowe na Pojezierzu Drawskim, przez które przepływa Drawa. Znane z sielawy, sandacza, szczupaka i okonia.',
      link: 'https://pl.wikipedia.org/wiki/Lubie',
    },
    {
      name: 'Jezioro Siecino',
      coords: [53.6, 15.92],
      desc: 'Czyste, głębokie jezioro na Pojezierzu Drawskim. Łowisko sielawy, siei, szczupaka i dużego okonia.',
      link: 'https://pl.wikipedia.org/wiki/Siecino',
    },
    {
      name: 'Jezioro Ińsko',
      coords: [53.44, 15.55],
      desc: 'Czyste jezioro rynnowe w Ińskim Parku Krajobrazowym. Występują sielawa, szczupak, okoń i lin.',
      link: 'https://pl.wikipedia.org/wiki/I%C5%84sko_(jezioro)',
    },
    {
      name: 'Jezioro Woświn',
      coords: [53.5, 15.4],
      desc: 'Duże jezioro na Pojezierzu Ińskim. Dobre łowisko sandacza, szczupaka, leszcza i węgorza.',
      link: 'https://pl.wikipedia.org/wiki/Wo%C5%9Bwin',
    },
    {
      name: 'Jezioro Bobięcińskie Wielkie',
      coords: [54.0, 16.83],
      desc: 'Największe jezioro lobeliowe w Polsce, o wyjątkowo czystej wodzie. Łowi się tu okonia, szczupaka i sielawę.',
      link: 'https://pl.wikipedia.org/wiki/Bobi%C4%99ci%C5%84skie_Wielkie',
    },
    {
      name: 'Jezioro Płoń',
      coords: [53.22, 14.93],
      desc: 'Płytkie, żyzne jezioro na Pojezierzu Myśliborskim koło Pyrzyc. Słynie z leszcza, sandacza, szczupaka i karasia.',
      link: 'https://pl.wikipedia.org/wiki/P%C5%82o%C5%84_(jezioro)',
    },
    {
      name: 'Rega',
      coords: [53.9, 15.27],
      desc: 'Jedna z najdłuższych rzek Przymorza, znane łowisko troci wędrownej. Poza trocią łowi się tu pstrąga, lipienia i szczupaka.',
      link: 'https://pl.wikipedia.org/wiki/Rega',
    },
    {
      name: 'Łeba (rzeka)',
      coords: [54.6, 17.7],
      desc: 'Rzeka przymorska wpadająca do jeziora Łebsko. Łowisko troci wędrownej, pstrąga potokowego i lipienia.',
      link: 'https://pl.wikipedia.org/wiki/%C5%81eba_(rzeka)',
    },
    {
      name: 'Łupawa',
      coords: [54.45, 17.25],
      desc: 'Bystra rzeka Pomorza wypływająca z jeziora Jasień. Ceniona przez muszkarzy — pstrąg potokowy, lipień i troć.',
      link: 'https://pl.wikipedia.org/wiki/%C5%81upawa_(rzeka)',
    },
    {
      name: 'Wieprza',
      coords: [54.25, 16.65],
      desc: 'Rzeka przymorska uchodząca do Bałtyku w Darłowie. Jedno z najlepszych łowisk troci i łososia na Pomorzu.',
      link: 'https://pl.wikipedia.org/wiki/Wieprza',
    },
    {
      name: 'Brda',
      coords: [53.8, 17.6],
      desc: 'Rzeka łącząca jeziora Borów Tucholskich, popularny szlak kajakowo-wędkarski. Łowi się pstrąga, lipienia, szczupaka i klenia.',
      link: 'https://pl.wikipedia.org/wiki/Brda_(rzeka)',
    },
    {
      name: 'Wierzyca',
      coords: [53.95, 18.45],
      desc: 'Kręta rzeka Pojezierza Kaszubskiego i Kociewia, dopływ Wisły. Występują pstrąg potokowy, kleń, jaź i szczupak.',
      link: 'https://pl.wikipedia.org/wiki/Wierzyca',
    },
    {
      name: 'Radunia',
      coords: [54.27, 18.25],
      desc: 'Bystra kaszubska rzeka o górskim charakterze, łącząca jeziora raduńskie. Łowisko pstrąga potokowego i lipienia.',
      link: 'https://pl.wikipedia.org/wiki/Radunia',
    },
    {
      name: 'Ina',
      coords: [53.3, 15.05],
      desc: 'Rzeka Pomorza Zachodniego, dopływ Odry, znana z corocznych tarlisk troci. Łowi się tu troć, pstrąga, klenia i szczupaka.',
      link: 'https://pl.wikipedia.org/wiki/Ina',
    },
    {
      name: 'Płonia',
      coords: [53.3, 14.7],
      desc: 'Rzeka łącząca jezioro Płoń z jeziorem Dąbie. W górnym biegu pstrąg potokowy, w dolnym szczupak, okoń i jaź.',
      link: 'https://pl.wikipedia.org/wiki/P%C5%82onia_(rzeka)',
    },
    {
      name: 'Piława',
      coords: [53.55, 16.35],
      desc: 'Dopływ Gwdy płynący przez Pojezierze Wałeckie i poligon drawski. Łowisko pstrąga, lipienia, szczupaka i okonia.',
      link: 'https://pl.wikipedia.org/wiki/Pi%C5%82awa_(dop%C5%82yw_Gwdy)',
    },
    {
      name: 'Nogat',
      coords: [54.1, 19.2],
      desc: 'Ramię ujściowe Wisły płynące przez Żuławy do Zalewu Wiślanego. Słynie z sandacza, szczupaka, leszcza i bolenia.',
      link: 'https://pl.wikipedia.org/wiki/Nogat',
    },
    {
      name: 'Szkarpawa',
      coords: [54.3, 19.05],
      desc: 'Żuławskie ramię Wisły uchodzące do Zalewu Wiślanego. Spokojna woda pełna szczupaka, sandacza, leszcza i suma.',
      link: 'https://pl.wikipedia.org/wiki/Szkarpawa',
    },
    {
      name: 'Zalew Wiślany',
      coords: [54.4, 19.5],
      desc: 'Rozległy, płytki zalew oddzielony od Bałtyku Mierzeją Wiślaną. Słynne łowisko sandacza, okonia, leszcza i węgorza.',
      link: 'https://pl.wikipedia.org/wiki/Zalew_Wi%C5%9Blany',
    },
    {
      name: 'Martwa Wisła',
      coords: [54.36, 18.72],
      desc: 'Dawne ujściowe ramię Wisły w Gdańsku, woda lekko słonawa. Znane łowisko sandacza, okonia, bolenia i troci.',
      link: 'https://pl.wikipedia.org/wiki/Martwa_Wis%C5%82a',
    },
    {
      name: 'Zatoka Gdańska',
      coords: [54.5, 18.8],
      desc: 'Bałtycka zatoka z plażami i molami od Gdańska po Hel. Wędkarstwo morskie: dorsz, śledź, płastugi i troć wędrowna.',
      link: 'https://pl.wikipedia.org/wiki/Zatoka_Gda%C5%84ska',
    },
    {
      name: 'Motława',
      coords: [54.33, 18.68],
      desc: 'Spokojna żuławska rzeka przepływająca przez Gdańsk. Łowisko leszcza, płoci, szczupaka, okonia i jazia.',
      link: 'https://pl.wikipedia.org/wiki/Mot%C5%82awa',
    },

    // --- Wielkopolska, Lubuskie, Kujawy, Łódzkie, Mazowsze ---
    {
      name: 'Jezioro Raczyńskie',
      coords: [52.25, 17.16],
      desc: 'Znane łowisko w Zaniemyślu w Wielkopolsce. Łowi się tu leszcze, szczupaki, okonie i liny.',
      link: 'https://pl.wikipedia.org/wiki/Jezioro_Raczy%C5%84skie',
    },
    {
      name: 'Jezioro Niesłysz',
      coords: [52.22, 15.39],
      desc: 'Największe jezioro Pojezierza Lubuskiego o wyjątkowo czystej wodzie. Występują sielawa, sieja, szczupak i okoń.',
      link: 'https://pl.wikipedia.org/wiki/Nies%C5%82ysz',
    },
    {
      name: 'Jezioro Sławskie',
      coords: [51.89, 16.02],
      desc: 'Największe jezioro Lubuskiego, zwane Śląskim Morzem. Bogate w leszcze, sandacze, szczupaki i węgorze.',
      link: 'https://pl.wikipedia.org/wiki/Jezioro_S%C5%82awskie',
    },
    {
      name: 'Jezioro Łagowskie',
      coords: [52.32, 15.30],
      desc: 'Głębokie jezioro rynnowe w Łagowskim Parku Krajobrazowym. Łowiska sielawy, szczupaka i okonia.',
      link: 'https://pl.wikipedia.org/wiki/Jezioro_%C5%81agowskie',
    },
    {
      name: 'Jezioro Trześniowskie',
      coords: [52.35, 15.30],
      desc: 'Głębokie (do 58 m) jezioro rynnowe koło Łagowa o krystalicznej wodzie. Sielawa, sieja, szczupak i okoń.',
      link: 'https://pl.wikipedia.org/wiki/Trze%C5%9Bniowskie',
    },
    {
      name: 'Jezioro Lednica',
      coords: [52.53, 17.37],
      desc: 'Historyczne jezioro rynnowe koło Gniezna. Dobre łowisko leszcza, szczupaka, lina i okonia.',
      link: 'https://pl.wikipedia.org/wiki/Lednica_(jezioro)',
    },
    {
      name: 'Jezioro Kierskie',
      coords: [52.47, 16.79],
      desc: 'Duże jezioro na obrzeżach Poznania, popularne wśród żeglarzy i wędkarzy. Sandacz, leszcz, szczupak i węgorz.',
      link: 'https://pl.wikipedia.org/wiki/Jezioro_Kierskie',
    },
    {
      name: 'Jezioro Maltańskie',
      coords: [52.40, 16.98],
      desc: 'Sztuczny zbiornik na Cybinie w Poznaniu. Miejskie łowisko karpia, leszcza, płoci i szczupaka.',
      link: 'https://pl.wikipedia.org/wiki/Jezioro_Malta%C5%84skie',
    },
    {
      name: 'Jezioro Strzeszyńskie',
      coords: [52.46, 16.86],
      desc: 'Czyste jezioro rynnowe w granicach Poznania. Łowi się okonie, płocie, liny i szczupaki.',
      link: 'https://pl.wikipedia.org/wiki/Jezioro_Strzeszy%C5%84skie',
    },
    {
      name: 'Jezioro Góreckie',
      coords: [52.27, 16.80],
      desc: 'Malownicze jezioro w Wielkopolskim Parku Narodowym (wędkowanie ograniczone strefami ochrony). Szczupak, okoń, lin.',
      link: 'https://pl.wikipedia.org/wiki/Jezioro_G%C3%B3reckie',
    },
    {
      name: 'Jezioro Dominickie',
      coords: [51.86, 16.27],
      desc: 'Duże jezioro koło Boszkowa na Pojezierzu Sławskim. Popularne łowisko leszcza, szczupaka, sandacza i węgorza.',
      link: 'https://pl.wikipedia.org/wiki/Jezioro_Dominickie',
    },
    {
      name: 'Jezioro Zbąszyńskie',
      coords: [52.26, 15.91],
      desc: 'Przepływowe jezioro na rzece Obrze. Płytkie i żyzne, obfituje w leszcze, sandacze, szczupaki i karpie.',
      link: 'https://pl.wikipedia.org/wiki/Jezioro_Zb%C4%85szy%C5%84skie',
    },
    {
      name: 'Jezioro Chrzypskie',
      coords: [52.59, 16.20],
      desc: 'Jezioro na Pojezierzu Międzychodzko-Sierakowskim. Dobre łowisko lina, leszcza, szczupaka i okonia.',
      link: 'https://pl.wikipedia.org/wiki/Jezioro_Chrzypskie',
    },
    {
      name: 'Jezioro Bytyńskie',
      coords: [52.49, 16.49],
      desc: 'Rozległe, płytkie jezioro z wyspami na zachód od Poznania. Słynie z dużych leszczy, szczupaków i karpi.',
      link: 'https://pl.wikipedia.org/wiki/Jezioro_Byty%C5%84skie',
    },
    {
      name: 'Jezioro Niedzięgiel',
      coords: [52.54, 17.73],
      desc: 'Czyste jezioro koło Skorzęcina na Pojezierzu Gnieźnieńskim. Sielawa, szczupak, okoń i lin.',
      link: 'https://pl.wikipedia.org/wiki/Niedzi%C4%99giel',
    },
    {
      name: 'Jezioro Ślesińskie',
      coords: [52.36, 18.09],
      desc: 'Jezioro w ciągu kanału Warta-Gopło koło Konina, podgrzewane wodami z elektrowni. Sandacz, leszcz, karp i amur.',
      link: 'https://pl.wikipedia.org/wiki/Jezioro_%C5%9Alesi%C5%84skie',
    },
    {
      name: 'Jezioro Licheńskie',
      coords: [52.31, 18.34],
      desc: 'Podgrzewane jezioro konińskiego systemu chłodzenia elektrowni. Całoroczne łowisko karpia, amura, tołpygi i sandacza.',
      link: 'https://pl.wikipedia.org/wiki/Jezioro_Liche%C5%84skie',
    },
    {
      name: 'Jezioro Pątnowskie',
      coords: [52.31, 18.25],
      desc: 'Podgrzewany zbiornik systemu jezior konińskich. Znane łowisko karpia, amura i sandacza, dostępne zimą.',
      link: 'https://pl.wikipedia.org/wiki/Jezioro_P%C4%85tnowskie',
    },
    {
      name: 'Jezioro Głuszyńskie',
      coords: [52.52, 18.65],
      desc: 'Rynnowe jezioro na Kujawach o wydłużonym kształcie. Żyzna woda z leszczem, sandaczem, szczupakiem i węgorzem.',
      link: 'https://pl.wikipedia.org/wiki/Jezioro_G%C5%82uszy%C5%84skie',
    },
    {
      name: 'Jezioro Borzymowskie',
      coords: [52.50, 18.95],
      desc: 'Jezioro na Pojezierzu Kujawskim koło Chodcza. Łowisko leszcza, szczupaka, lina i karasia.',
      link: 'https://pl.wikipedia.org/wiki/Jezioro_Borzymowskie',
    },
    {
      name: 'Jezioro Modzerowskie',
      coords: [52.43, 18.86],
      desc: 'Płytkie, żyzne jezioro na Kujawach. Dobre miejsce na leszcza, karasia, lina i szczupaka.',
      link: 'https://pl.wikipedia.org/wiki/Jezioro_Modzerowskie',
    },
    {
      name: 'Zalew Koronowski',
      coords: [53.27, 17.95],
      desc: 'Rozległy zbiornik zaporowy na Brdzie koło Bydgoszczy o krętej linii brzegowej. Sandacz, szczupak, okoń i leszcz.',
      link: 'https://pl.wikipedia.org/wiki/Zalew_Koronowski',
    },
    {
      name: 'Noteć',
      coords: [52.94, 16.45],
      desc: 'Spokojna, nizinna rzeka kanalizowana licznymi stopniami. Obfituje w leszcze, sandacze, sumy i szczupaki.',
      link: 'https://pl.wikipedia.org/wiki/Note%C4%87',
    },
    {
      name: 'Obra',
      coords: [52.30, 15.78],
      desc: 'Nizinna rzeka zachodniej Wielkopolski łącząca liczne jeziora. Łowisko szczupaka, lina, leszcza i węgorza.',
      link: 'https://pl.wikipedia.org/wiki/Obra_(rzeka)',
    },
    {
      name: 'Prosna',
      coords: [51.70, 18.10],
      desc: 'Lewy dopływ Warty płynący przez Kalisz. Kleń, jaź, płoć, okoń oraz szczupak na spokojniejszych odcinkach.',
      link: 'https://pl.wikipedia.org/wiki/Prosna',
    },
    {
      name: 'Bóbr',
      coords: [51.80, 15.55],
      desc: 'Rzeka o podgórskim charakterze, w dolnym biegu płynąca przez Lubuskie. Pstrąg, lipień, kleń i boleń.',
      link: 'https://pl.wikipedia.org/wiki/B%C3%B3br_(rzeka)',
    },
    {
      name: 'Nysa Łużycka',
      coords: [51.95, 14.72],
      desc: 'Graniczna rzeka zachodniej Polski o zróżnicowanym nurcie. Kleń, boleń, szczupak, okoń i sum.',
      link: 'https://pl.wikipedia.org/wiki/Nysa_%C5%81u%C5%BCycka',
    },
    {
      name: 'Bzura',
      coords: [52.20, 19.90],
      desc: 'Nizinna rzeka Mazowsza i Ziemi Łódzkiej. W czystszych odcinkach kleń i jaź, ponadto płoć, okoń i szczupak.',
      link: 'https://pl.wikipedia.org/wiki/Bzura',
    },
    {
      name: 'Rawka',
      coords: [52.05, 20.25],
      desc: 'Meandrująca rzeka-rezerwat przyrody, dopływ Bzury. Łowisko pstrąga potokowego, klenia i jelca.',
      link: 'https://pl.wikipedia.org/wiki/Rawka_(rzeka)',
    },
    {
      name: 'Wkra',
      coords: [52.55, 20.55],
      desc: 'Czysta, piaszczysta rzeka północnego Mazowsza. Popularne łowisko klenia, jazia, szczupaka i okonia.',
      link: 'https://pl.wikipedia.org/wiki/Wkra',
    },
    {
      name: 'Liwiec',
      coords: [52.30, 21.95],
      desc: 'Naturalna, meandrująca rzeka wschodniego Mazowsza, dopływ Bugu. Kleń, jaź, szczupak, okoń i jelec.',
      link: 'https://pl.wikipedia.org/wiki/Liwiec',
    },
    {
      name: 'Świder',
      coords: [52.10, 21.30],
      desc: 'Mała, malownicza rzeka pod Warszawą objęta ochroną rezerwatową. Kleń, jelec, płoć i okoń.',
      link: 'https://pl.wikipedia.org/wiki/%C5%9Awider_(rzeka)',
    },
    {
      name: 'Ner',
      coords: [51.95, 18.95],
      desc: 'Rzeka Ziemi Łódzkiej, dopływ Warty, o odradzającym się rybostanie. Płoć, leszcz, okoń i szczupak.',
      link: 'https://pl.wikipedia.org/wiki/Ner',
    },
    {
      name: 'Zbiornik Cieszanowice',
      coords: [51.18, 19.80],
      desc: 'Zbiornik zaporowy na rzece Luciąży koło Piotrkowa Trybunalskiego. Łowisko sandacza, szczupaka, leszcza i karpia.',
      link: 'https://pl.wikipedia.org/wiki/Zbiornik_Cieszanowice',
    },
    {
      name: 'Jezioro Zdworskie',
      coords: [52.47, 19.70],
      desc: 'Największe jezioro Pojezierza Gostynińskiego na Mazowszu. Płytkie i żyzne, z leszczem, karasiem, linem i szczupakiem.',
      link: 'https://pl.wikipedia.org/wiki/Jezioro_Zdworskie',
    },

    // --- Dolny Śląsk, Opolszczyzna, Śląsk, Małopolska, Podkarpacie, Świętokrzyskie, Lubelszczyzna ---
    {
      name: 'Jezioro Pilchowickie',
      coords: [51.00, 15.63],
      desc: 'Górski zbiornik zaporowy na Bobrze u stóp Karkonoszy. Łowi się tu szczupaki, okonie, sandacze i pstrągi.',
      link: 'https://pl.wikipedia.org/wiki/Jezioro_Pilchowickie',
    },
    {
      name: 'Jezioro Złotnickie',
      coords: [51.02, 15.42],
      desc: 'Malowniczy zbiornik zaporowy na Kwisie o skalistych brzegach. Dobre łowisko szczupaka, okonia i lina.',
      link: 'https://pl.wikipedia.org/wiki/Jezioro_Z%C5%82otnickie',
    },
    {
      name: 'Jezioro Leśniańskie',
      coords: [51.03, 15.35],
      desc: 'Najstarszy zbiornik zaporowy w Polsce, położony na Kwisie. Występują tu szczupaki, sandacze, okonie i leszcze.',
      link: 'https://pl.wikipedia.org/wiki/Jezioro_Le%C5%9Bnia%C5%84skie',
    },
    {
      name: 'Zbiornik Słup',
      coords: [51.07, 16.16],
      desc: 'Rozległy zbiornik zaporowy na Nysie Szalonej koło Jawora. Znany z dużych sandaczy, szczupaków i karpi.',
      link: 'https://pl.wikipedia.org/wiki/Zbiornik_S%C5%82up',
    },
    {
      name: 'Zbiornik Bukówka',
      coords: [50.72, 16.05],
      desc: 'Wysokogórski zbiornik na Bobrze koło Lubawki. Czysta, zimna woda sprzyja pstrągom, okoniom i szczupakom.',
      link: 'https://pl.wikipedia.org/wiki/Zbiornik_Buk%C3%B3wka',
    },
    {
      name: 'Zbiornik Sosnówka',
      coords: [50.84, 15.72],
      desc: 'Zbiornik wodny u podnóża Karkonoszy o bardzo czystej wodzie. Łowisko okoni, szczupaków i pstrągów.',
      link: 'https://pl.wikipedia.org/wiki/Zbiornik_Sosn%C3%B3wka',
    },
    {
      name: 'Kwisa',
      coords: [51.00, 15.30],
      desc: 'Sudecka rzeka o charakterze górskim i podgórskim. Doskonałe łowisko pstrąga potokowego i lipienia.',
      link: 'https://pl.wikipedia.org/wiki/Kwisa',
    },
    {
      name: 'Nysa Kłodzka',
      coords: [50.45, 16.65],
      desc: 'Górska rzeka spływająca z Kotliny Kłodzkiej. Słynie z pstrągów, lipieni, a w dolnym biegu z brzan i kleni.',
      link: 'https://pl.wikipedia.org/wiki/Nysa_K%C5%82odzka',
    },
    {
      name: 'Stawy Milickie',
      coords: [51.52, 17.35],
      desc: 'Największy kompleks stawów rybnych w Europie, w dolinie Baryczy. Królestwo karpia, lina i szczupaka.',
      link: 'https://pl.wikipedia.org/wiki/Stawy_Milickie',
    },
    {
      name: 'Jezioro Nyskie',
      coords: [50.46, 17.30],
      desc: 'Duży zbiornik zaporowy na Nysie Kłodzkiej. Znane łowisko sandacza, szczupaka, okonia i leszcza.',
      link: 'https://pl.wikipedia.org/wiki/Jezioro_Nyskie',
    },
    {
      name: 'Jezioro Turawskie',
      coords: [50.72, 18.12],
      desc: 'Rozległy zbiornik na Małej Panwi koło Opola. Popularne łowisko sandacza, szczupaka, bolenia i leszcza.',
      link: 'https://pl.wikipedia.org/wiki/Jezioro_Turawskie',
    },
    {
      name: 'Mała Panew',
      coords: [50.70, 18.30],
      desc: 'Nizinna, meandrująca rzeka o piaszczystym dnie. Łowisko kleni, jazi, szczupaków i okoni.',
      link: 'https://pl.wikipedia.org/wiki/Ma%C5%82a_Panew',
    },
    {
      name: 'Dzierżno Duże',
      coords: [50.36, 18.55],
      desc: 'Duży zbiornik poprzemysłowy koło Gliwic. Słynie z dużych sandaczy, szczupaków i karpi.',
      link: 'https://pl.wikipedia.org/wiki/Dzier%C5%BCno_Du%C5%BCe',
    },
    {
      name: 'Jezioro Pławniowickie',
      coords: [50.39, 18.48],
      desc: 'Zbiornik w wyrobisku popiaskowym o czystej wodzie. Dobre łowisko okonia, sandacza, szczupaka i płoci.',
      link: 'https://pl.wikipedia.org/wiki/Jezioro_P%C5%82awniowickie',
    },
    {
      name: 'Pogoria III',
      coords: [50.36, 19.22],
      desc: 'Największe z jezior Pogorii w Dąbrowie Górniczej. Przejrzysta woda, liczne okonie, szczupaki i karpie.',
      link: 'https://pl.wikipedia.org/wiki/Pogoria_III',
    },
    {
      name: 'Zbiornik Kozłowa Góra',
      coords: [50.45, 18.94],
      desc: 'Płytki zbiornik zaporowy na Brynicy koło Piekar Śląskich. Znany z dużych szczupaków, linów i karasi.',
      link: 'https://pl.wikipedia.org/wiki/Zbiornik_Koz%C5%82owa_G%C3%B3ra',
    },
    {
      name: 'Zbiornik Dziećkowice',
      coords: [50.16, 19.18],
      desc: 'Głęboki zbiornik o bardzo czystej wodzie koło Mysłowic. Łowisko sielawy, siei, okonia i sandacza.',
      link: 'https://pl.wikipedia.org/wiki/Zbiornik_Dzie%C4%87kowice',
    },
    {
      name: 'Zbiornik Rybnicki',
      coords: [50.13, 18.51],
      desc: 'Podgrzewany zbiornik elektrowni Rybnik, łowisko czynne cały rok. Słynie z karpi, amurów i sumów.',
      link: 'https://pl.wikipedia.org/wiki/Zbiornik_Rybnicki',
    },
    {
      name: 'Jezioro Paprocańskie',
      coords: [50.09, 18.96],
      desc: 'Płytki, zarośnięty zbiornik w Tychach na rzece Gostyni. Dobre łowisko szczupaka, lina i karasia.',
      link: 'https://pl.wikipedia.org/wiki/Jezioro_Paproca%C5%84skie',
    },
    {
      name: 'Jezioro Międzybrodzkie',
      coords: [49.79, 19.21],
      desc: 'Górski zbiornik zaporowy na Sole w Beskidzie Małym. Łowi się tu sandacze, szczupaki, okonie i pstrągi.',
      link: 'https://pl.wikipedia.org/wiki/Jezioro_Mi%C4%99dzybrodzkie',
    },
    {
      name: 'Soła',
      coords: [49.70, 19.20],
      desc: 'Górska rzeka beskidzka o wartkim nurcie i kamienistym dnie. Znakomite łowisko pstrąga potokowego i lipienia.',
      link: 'https://pl.wikipedia.org/wiki/So%C5%82a',
    },
    {
      name: 'Jezioro Dobczyckie',
      coords: [49.87, 20.07],
      desc: 'Zbiornik zaporowy na Rabie, źródło wody dla Krakowa. Występują tu duże szczupaki, sandacze i pstrągi.',
      link: 'https://pl.wikipedia.org/wiki/Jezioro_Dobczyckie',
    },
    {
      name: 'Jezioro Klimkowskie',
      coords: [49.63, 21.13],
      desc: 'Górski zbiornik na rzece Ropie w Beskidzie Niskim. Czysta woda, łowisko szczupaka, okonia i pstrąga.',
      link: 'https://pl.wikipedia.org/wiki/Jezioro_Klimkowskie',
    },
    {
      name: 'Jezioro Mucharskie',
      coords: [49.80, 19.53],
      desc: 'Najmłodszy duży zbiornik zaporowy w Polsce, na rzece Skawie. Szybko rosnąca populacja okoni, szczupaków i sandaczy.',
      link: 'https://pl.wikipedia.org/wiki/Jezioro_Mucharskie',
    },
    {
      name: 'Jezioro Czchowskie',
      coords: [49.85, 20.68],
      desc: 'Zbiornik wyrównawczy na Dunajcu poniżej Rożnowa. Łowisko brzan, kleni, szczupaków i sandaczy.',
      link: 'https://pl.wikipedia.org/wiki/Jezioro_Czchowskie',
    },
    {
      name: 'Zalew Bagry (Kraków)',
      coords: [50.03, 19.99],
      desc: 'Popularny zalew w granicach Krakowa, powstały w wyrobisku. Łowi się tu karpie, liny, szczupaki i okonie.',
      link: 'https://pl.wikipedia.org/wiki/Bagry',
    },
    {
      name: 'Skawa',
      coords: [49.75, 19.60],
      desc: 'Beskidzka rzeka o charakterze górskim i podgórskim. Dobre łowisko pstrąga, lipienia i klenia.',
      link: 'https://pl.wikipedia.org/wiki/Skawa',
    },
    {
      name: 'Poprad',
      coords: [49.40, 20.70],
      desc: 'Górska rzeka przełamująca się przez Beskid Sądecki. Słynie z lipieni, pstrągów i dużych kleni.',
      link: 'https://pl.wikipedia.org/wiki/Poprad',
    },
    {
      name: 'Zbiornik Czaniec',
      coords: [49.86, 19.27],
      desc: 'Zbiornik wyrównawczy kaskady Soły o czystej, zimnej wodzie. Łowisko pstrągów, okoni i szczupaków.',
      link: 'https://pl.wikipedia.org/wiki/Zbiornik_Czaniec',
    },
    {
      name: 'Jezioro Myczkowskie',
      coords: [49.45, 22.42],
      desc: 'Niewielki zbiornik wyrównawczy na Sanie poniżej Soliny. Zimna woda sprzyja pstrągom, okoniom i szczupakom.',
      link: 'https://pl.wikipedia.org/wiki/Jezioro_Myczkowskie',
    },
    {
      name: 'Wisłok',
      coords: [49.90, 21.80],
      desc: 'Podkarpacka rzeka o górskim górnym i nizinnym dolnym biegu. Łowisko kleni, brzan, szczupaków i sumów.',
      link: 'https://pl.wikipedia.org/wiki/Wis%C5%82ok',
    },
    {
      name: 'Zalew Rzeszowski',
      coords: [50.00, 22.01],
      desc: 'Płytki zalew na Wisłoku w granicach Rzeszowa. Popularne miejskie łowisko karpia, leszcza i szczupaka.',
      link: 'https://pl.wikipedia.org/wiki/Zalew_Rzeszowski',
    },
    {
      name: 'Zbiornik Besko',
      coords: [49.56, 21.97],
      desc: 'Górski zbiornik zaporowy na Wisłoku koło Sieniawy. Czysta woda, łowisko szczupaka, okonia i pstrąga.',
      link: 'https://pl.wikipedia.org/wiki/Zbiornik_Besko',
    },
    {
      name: 'Osława',
      coords: [49.35, 22.10],
      desc: 'Dzika bieszczadzka rzeka, dopływ Sanu. Znakomite łowisko pstrąga potokowego, lipienia i klenia.',
      link: 'https://pl.wikipedia.org/wiki/Os%C5%82awa',
    },
    {
      name: 'Tanew',
      coords: [50.50, 22.70],
      desc: 'Roztoczańska rzeka o krystalicznej wodzie i piaszczystym dnie. Łowi się tu pstrągi, klenie, jazie i szczupaki.',
      link: 'https://pl.wikipedia.org/wiki/Tanew',
    },
    {
      name: 'Zbiornik Chańcza',
      coords: [50.60, 21.07],
      desc: 'Zbiornik zaporowy na Czarnej Staszowskiej. Znane łowisko sandacza, szczupaka, suma i karpia.',
      link: 'https://pl.wikipedia.org/wiki/Zbiornik_Cha%C5%84cza',
    },
    {
      name: 'Kamienna',
      coords: [51.05, 21.20],
      desc: 'Rzeka świętokrzyska przepływająca przez Ostrowiec i Starachowice. Łowisko kleni, jazi, okoni i szczupaków.',
      link: 'https://pl.wikipedia.org/wiki/Kamienna_(dop%C5%82yw_Wis%C5%82y)',
    },
    {
      name: 'Czarna Staszowska',
      coords: [50.50, 21.20],
      desc: 'Spokojna rzeka świętokrzyska płynąca przez lasy i stawy. Łowi się tu szczupaki, okonie, liny i płocie.',
      link: 'https://pl.wikipedia.org/wiki/Czarna_Staszowska',
    },
    {
      name: 'Zalew Kielecki',
      coords: [50.89, 20.63],
      desc: 'Miejski zalew na rzece Silnicy w Kielcach. Popularne łowisko karpia, karasia, płoci i szczupaka.',
      link: 'https://pl.wikipedia.org/wiki/Zalew_Kielecki',
    },
    {
      name: 'Nida',
      coords: [50.50, 20.50],
      desc: 'Leniwie meandrująca rzeka Ponidzia o ciepłej wodzie. Słynie z jazi, kleni, szczupaków i sumów.',
      link: 'https://pl.wikipedia.org/wiki/Nida',
    },
    {
      name: 'Zalew Zemborzycki',
      coords: [51.17, 22.52],
      desc: 'Duży zalew na Bystrzycy w granicach Lublina. Łowisko leszcza, karpia, sandacza i szczupaka.',
      link: 'https://pl.wikipedia.org/wiki/Zalew_Zemborzycki',
    },
    {
      name: 'Zbiornik Nielisz',
      coords: [50.80, 23.05],
      desc: 'Rozległy, płytki zbiornik na Wieprzu koło Zamościa. Znany z dużych szczupaków, sandaczy i karpi.',
      link: 'https://pl.wikipedia.org/wiki/Zbiornik_Nielisz',
    },
    {
      name: 'Wieprz',
      coords: [51.20, 22.60],
      desc: 'Najdłuższa rzeka Lubelszczyzny, mocno meandrująca. Łowisko szczupaków, jazi, kleni i sumów.',
      link: 'https://pl.wikipedia.org/wiki/Wieprz',
    },
  ];

  const map = L.map(el).setView([52.1, 19.4], 6);
  L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
    maxZoom: 18,
    attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>',
  }).addTo(map);

  // Grupowanie znaczników — przy 200 łowiskach pojedyncze pinezki zlewałyby się przy małym zoomie.
  const cluster = typeof L.markerClusterGroup === 'function' ? L.markerClusterGroup() : L.layerGroup();
  LOWISKA.forEach((l) => {
    cluster.addLayer(
      L.marker(l.coords).bindPopup(
        '<strong>' + l.name + '</strong><br>' + l.desc +
        '<br><a href="' + l.link + '" target="_blank" rel="noopener">Więcej o łowisku →</a>'
      )
    );
  });
  map.addLayer(cluster);
})();
